# Generated by Django 4.0.5 on 2022-06-10 23:36

from django.db import migrations, models
import django.db.models.deletion
import registration.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300, null=True)),
                ('mobile', models.CharField(default='', max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('academy', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('en', models.CharField(max_length=100, null=True)),
                ('include', models.BooleanField(db_index=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCity',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=200, null=True)),
                ('include', models.BooleanField(db_index=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterColumn',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('columnid', models.CharField(db_index=True, max_length=300, null=True)),
                ('label_key', models.CharField(max_length=300, null=True)),
                ('includep1', models.BooleanField(db_index=True, default=True, null=True)),
                ('includep2', models.BooleanField(db_index=True, default=True, null=True)),
                ('type', models.CharField(max_length=300, null=True)),
                ('orderid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDocument',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('keydata', models.CharField(db_index=True, max_length=200, null=True)),
                ('en', models.CharField(max_length=300, null=True)),
                ('hi', models.CharField(max_length=300, null=True)),
                ('mr', models.CharField(max_length=300, null=True)),
                ('asm', models.CharField(max_length=300, null=True)),
                ('ben', models.CharField(max_length=300, null=True)),
                ('odia', models.CharField(max_length=300, null=True)),
                ('bodo', models.CharField(max_length=300, null=True)),
                ('include', models.BooleanField(db_index=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterGroup',
            fields=[
                ('id', models.CharField(db_index=True, max_length=150, primary_key=True, serialize=False)),
                ('group', models.CharField(db_index=True, max_length=300, null=True)),
                ('year', models.CharField(db_index=True, max_length=300, null=True)),
                ('start', models.DateField(db_index=True)),
                ('end', models.DateField(db_index=True)),
                ('include', models.BooleanField(db_index=True, default=True, null=True)),
                ('orderid', models.IntegerField(null=True)),
                ('gender', models.CharField(db_index=True, default='Female', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLabels',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('keydata', models.CharField(db_index=True, max_length=200, null=True)),
                ('en', models.TextField(null=True)),
                ('hi', models.TextField(null=True)),
                ('mr', models.TextField(null=True)),
                ('asm', models.TextField(null=True)),
                ('ben', models.TextField(null=True)),
                ('odia', models.TextField(null=True)),
                ('bodo', models.TextField(null=True)),
                ('extrainfo', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPosition',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('position', models.CharField(db_index=True, max_length=200, null=True)),
                ('label', models.CharField(db_index=True, max_length=200, null=True)),
                ('type', models.CharField(db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterRoles',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('en', models.CharField(max_length=100, null=True)),
                ('include', models.BooleanField(db_index=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSeason',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('en', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('include', models.BooleanField(db_index=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterState',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('country_id', models.CharField(max_length=300, null=True)),
                ('include', models.BooleanField(db_index=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ikfuniqueid', models.CharField(max_length=200, null=True)),
                ('playeruploadid', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(db_index=True, max_length=10, null=True)),
                ('razorpay_order_id', models.CharField(max_length=300, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=300, null=True)),
                ('razorpay_signature', models.CharField(max_length=400, null=True)),
                ('error_code', models.CharField(max_length=300, null=True)),
                ('error_description', models.CharField(max_length=400, null=True)),
                ('error_source', models.CharField(max_length=300, null=True)),
                ('error_reason', models.CharField(max_length=300, null=True)),
                ('error_meta_order_id', models.CharField(max_length=300, null=True)),
                ('error_meta_payment_id', models.CharField(max_length=300, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('icon', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=300, null=True)),
                ('type_of_link', models.CharField(db_index=True, max_length=100, null=True)),
                ('include', models.BooleanField(db_index=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(db_index=True, max_length=400, null=True)),
                ('image', models.ImageField(storage=registration.storage.OverwriteStorage(), upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(db_index=True, max_length=400, null=True)),
                ('file', models.ImageField(storage=registration.storage.OverwriteStorage(), upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('gender', models.CharField(db_index=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300, null=True)),
                ('height', models.CharField(db_index=True, max_length=10)),
                ('weight', models.CharField(db_index=True, max_length=10)),
                ('mobile', models.CharField(default='', max_length=10, null=True)),
                ('radiomobile', models.BooleanField(null=True)),
                ('whatsapp', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ipv4', models.GenericIPAddressField(null=True)),
                ('ipv6', models.GenericIPAddressField(null=True)),
                ('ikfuniqueid', models.CharField(db_index=True, max_length=200, null=True)),
                ('address_line1', models.TextField(null=True)),
                ('address_line2', models.TextField(null=True)),
                ('pincode', models.IntegerField(db_index=True, null=True)),
                ('pic_file', models.CharField(max_length=300, null=True)),
                ('document_id_number', models.CharField(max_length=300, null=True)),
                ('document_id_file', models.CharField(max_length=300, null=True)),
                ('playeruploadid', models.CharField(max_length=300, null=True)),
                ('dob', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(db_index=True, max_length=10, null=True)),
                ('razorpay_order_id', models.CharField(max_length=300, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=300, null=True)),
                ('razorpay_signature', models.CharField(max_length=400, null=True)),
                ('error_code', models.CharField(max_length=300, null=True)),
                ('error_description', models.CharField(max_length=400, null=True)),
                ('error_source', models.CharField(max_length=300, null=True)),
                ('error_reason', models.CharField(max_length=300, null=True)),
                ('error_meta_order_id', models.CharField(max_length=300, null=True)),
                ('error_meta_payment_id', models.CharField(max_length=300, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercategory', verbose_name='master_category_id')),
                ('document_id_selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterdocument', verbose_name='document')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastergroup', verbose_name='master_group_id')),
                ('primary_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_position2', to='registration.masterposition', verbose_name='primary position')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterseason', verbose_name='master_season_id')),
                ('secondary_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_position', to='registration.masterposition', verbose_name='secondary position')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='registration.masterstate', verbose_name='state')),
                ('tournament_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercity', verbose_name='master city')),
                ('tournament_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state2', to='registration.masterstate', verbose_name='master state')),
                ('whoisfilling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterroles', verbose_name='master_roles_id')),
            ],
        ),
        migrations.CreateModel(
            name='MasterGroupCity',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('include', models.BooleanField(db_index=True, default=True, null=True)),
                ('cityid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercity', verbose_name='master_city_id')),
                ('groupid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastergroup', verbose_name='master group id')),
            ],
        ),
        migrations.AddField(
            model_name='mastercity',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterstate', verbose_name='State ID'),
        ),
        migrations.CreateModel(
            name='MasterAmount',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('include', models.BooleanField(db_index=True, default=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercategory', verbose_name='master_category_id')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercity', verbose_name='master_city_id')),
                ('coach_or_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterroles', verbose_name='master_roles_id')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastergroup', verbose_name='master_group_id')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterseason', verbose_name='master_season_id')),
            ],
        ),
    ]
