# Generated by Django 4.0.5 on 2022-06-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPartner',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=300, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=300, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('include', models.BooleanField(db_index=True, default=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercategory', verbose_name='master_category_id')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercity', verbose_name='master_city_id')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterseason', verbose_name='master_season_id')),
            ],
        ),
    ]
