# Generated by Django 4.0.5 on 2022-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_mastercategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCoachLabels',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('keydata', models.CharField(db_index=True, max_length=200, null=True)),
                ('en', models.TextField(null=True)),
                ('hi', models.TextField(null=True)),
                ('mr', models.TextField(null=True)),
                ('asm', models.TextField(null=True)),
                ('ben', models.TextField(null=True)),
                ('odia', models.TextField(null=True)),
                ('bodo', models.TextField(null=True)),
                ('extrainfo', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Master Coach Label',
                'verbose_name_plural': 'Master Coach Labels',
            },
        ),
    ]
