# Generated by Django 4.0.5 on 2022-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_mastercoachlabels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='password',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='userid',
        ),
        migrations.AddField(
            model_name='coach',
            name='academy_name',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='academy_phone',
            field=models.CharField(default='NA', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='name',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='phone',
            field=models.CharField(db_index=True, default='NA', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='tournament_city',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='tournament_state',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
