# Generated by Django 4.0.5 on 2022-06-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_coach_options_remove_coach_academy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_id',
        ),
    ]
