# Generated by Django 4.0.5 on 2022-06-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_masterdatelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='first_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='last_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mobile',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='first_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='last_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='mobile',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
