# Generated by Django 4.0.5 on 2022-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_coach_coach_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
