# Generated by Django 4.0.4 on 2022-06-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_first_name_upload_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='mobile',
            new_name='mobilenumberupload',
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='mobile',
            new_name='mobilenumberupload',
        ),
    ]
