# Generated by Django 4.0.5 on 2022-06-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_coach_coach_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachModel',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=10, unique=True)),
                ('tournament_state', models.CharField(db_index=True, max_length=200)),
                ('tournament_city', models.CharField(db_index=True, max_length=200)),
                ('academy_name', models.CharField(max_length=200)),
                ('academy_phone', models.CharField(max_length=200, unique=True)),
                ('coach_id', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'CoachModel',
                'verbose_name_plural': 'CoachModels',
            },
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
