# Generated by Django 4.0.5 on 2022-06-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_coachmodel_delete_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachmodel',
            old_name='email',
            new_name='coach_email',
        ),
        migrations.RenameField(
            model_name='coachmodel',
            old_name='phone',
            new_name='coach_mobile',
        ),
        migrations.RenameField(
            model_name='coachmodel',
            old_name='name',
            new_name='coach_name',
        ),
        migrations.AddField(
            model_name='coachmodel',
            name='academy_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coachmodel',
            name='academy_mobile',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coachmodel',
            name='academy_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coachmodel',
            name='academy_phone',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
