# Generated by Django 4.0.5 on 2022-06-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_rename_email_coachmodel_coach_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmodel',
            name='tournament_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mastercity', verbose_name='master city'),
        ),
        migrations.AlterField(
            model_name='coachmodel',
            name='tournament_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterstate', verbose_name='master state'),
        ),
    ]
