# Generated by Django 4.0.5 on 2022-06-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_coachmodel_tournament_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachmodel',
            name='academy_phone',
        ),
    ]
