# Generated by Django 4.0.5 on 2022-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_remove_coachmodel_academy_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmodel',
            name='academy_mobile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
