# Generated by Django 4.0.5 on 2022-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_rename_mobile_upload_mobilenumberupload_and_more'),
        ('registration', '0014_player_coach_id'),
    ]

    operations = [
    ]
