# Generated by Django 4.0.5 on 2022-07-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_player_position1_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpartner',
            name='dateofevent',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='asm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='ben',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='bodo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='extrainfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='keydata',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercoachlabels',
            name='odia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercolumn',
            name='columnid',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mastercolumn',
            name='includep1',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercolumn',
            name='includep2',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercolumn',
            name='label_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mastercolumn',
            name='orderid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercolumn',
            name='type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='asm',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='ben',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='bodo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='hi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='include',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='mr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterdocument',
            name='odia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='asm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='ben',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='bodo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='extrainfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlabels',
            name='odia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='address_line1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='address_line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='coach_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='document_id_file',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='document_id_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='document_id_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.masterdocument', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='error_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='error_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='error_meta_order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='error_meta_payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='error_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='error_source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='ipv4',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='player',
            name='pic_file',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pincode',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='playeruploadid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='radiomobile',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='registration.masterstate', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='userid',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
